# Generated by Django 2.2.5 on 2019-09-18 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='新建文件', max_length=200, verbose_name='文件名')),
                ('filetype', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件类型')),
                ('depth', models.IntegerField(default=1, verbose_name='目录深度')),
                ('url', models.CharField(default='', max_length=200, verbose_name='相对路径')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('modifytime', models.DateField(auto_now=True, verbose_name='最后修改时间')),
                ('createtime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='新建文件夹', max_length=200)),
                ('depth', models.IntegerField(default=1, verbose_name='目录深度')),
                ('url', models.CharField(default='', max_length=200, verbose_name='相对路径')),
                ('createtime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_son', to='dbmysql.Folder', verbose_name='父文件夹')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
                'ordering': ['id'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.BooleanField(choices=[(0, '可读'), (1, '读写')], default=1)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissionFile', to='dbmysql.File', verbose_name='文件权限')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissionFolder', to='dbmysql.Folder', verbose_name='文件夹权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='pfolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmysql.Folder', verbose_name='所属文件夹'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'pfolder')},
        ),
    ]
